# Generated by Django 6.1.1 on 2026-09-20 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Bangladeshi phone number (e.g. +88017XXXXXXXX or 017XXXXXXXX).', regex='^(?:\\+?88|88)?01[3-9]\\d{8}$')]),
        ),
    ]
